workflows:
  build-android:
    name: Build Android APK
    environment:
      node: latest
      npm: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build APK with EAS
        script: npx eas build -p android --profile production --local --non-interactive
    artifacts:
      - android/app/build/outputs/**/*.apk
