workflows:
  build-apk:
    name: Build APK
    max_build_duration: 60
    environment:
      node: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build APK with Expo
        script: npx expo build:android -t apk
    artifacts:
      - "**/*.apk"
